language: ruby
before_script: "cp config/application.yml{.example,} && RAILS_ENV=development bundle exec rake db:migrate db:test:prepare"
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
